version: "3"
services:
  db:
    image: mariadb
    container_name: charkchalk-db
    restart: always
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PORT: ${DB_PORT}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: charkchalk-phpmyadmin
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
